### ISSUE TITLE
CAN: Automatic generation of stable baudrates

### ISSUE THREAD

**Issue by hatrx** [UnicornRaceEngineering/g5-nodes#9]
Niceness is to choose a baudrate from automaticly generated list
of baudrates.
Right now, only people with a intimate relationship with the CAN
standard and a TI-89 can calculate a stable baudrate.
A stand alone application or an integrated solution would be
very nice indeed.

**Comment by FnuGk** [comment]
We use https://github.com/FnuGk/can-config for generating correct baudrates
